const mongoose = require('mongoose');

const movieSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, maxLength: 500 },
  posterUrl: { type: String, required: true },
  backdropUrl: { type: String },
  trailerUrl: { type: String },
  videoUrl: { type: String }, // For single quality or backward compatibility

  // Categorization
  genre: { type: [String] },
  tags: { type: [String] },
  collectionName: { type: String },
  regionalAvailability: { type: [String], default: ['Global'] },
  contentRating: { type: String, enum: ['G', 'PG', 'PG-13', 'R'], default: 'PG-13' },

  // Metadata
  duration: { type: String },
  year: { type: Number },
  language: { type: String, default: 'English' },
  country: { type: String },

  // Settings & Flags
  status: { type: String, enum: ['Public', 'Draft', 'Coming Soon'], default: 'Draft' },
  isPremium: { type: Boolean, default: false },
  isDownloadable: { type: Boolean, default: true },
  isFeatured: { type: Boolean, default: false },
  isOriginal: { type: Boolean, default: false },
  isTvShow: { type: Boolean, default: false },

  // Media Assets
  gallery: { type: [String] },

  // Video Sources (Multi-quality)
  sources: {
    '480p': { type: String },
    '720p': { type: String },
    '1080p': { type: String },
    '4K': { type: String }
  },
  useDRM: { type: Boolean, default: false },

  // Subtitles
  subtitles: [{
    language: { type: String },
    url: { type: String },
    isAutoGenerated: { type: Boolean, default: false }
  }],

  // Monetization
  rentPrice: { type: Number, default: 0 },
  buyPrice: { type: Number, default: 0 },
  rentalDuration: { type: Number, default: 48 }, // hours
  premiumOnly: { type: Boolean, default: false },

  // TV Show Specific
  seasons: [{
    number: { type: Number },
    status: { type: String, enum: ['Ongoing', 'Completed'], default: 'Completed' },
    episodes: [{
      number: { type: Number },
      title: { type: String },
      thumbnailUrl: { type: String },
      duration: { type: String },
      videoUrl: { type: String },
      isDownloadable: { type: Boolean, default: true },
      sources: {
        '480p': { type: String },
        '720p': { type: String },
        '1080p': { type: String },
        '4K': { type: String }
      }
    }]
  }],

  rating: { type: Number, default: 0 },
  views: { type: Number, default: 0 },
  isTrending: { type: Boolean, default: false },
}, { timestamps: true });

const Movie = mongoose.models.Movie || mongoose.model('Movie', movieSchema);

module.exports = Movie;
