name: Flutter Build APK

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLCACHE"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --no-pub

      # Build APK removed from here to prevent redundant resource-heavy builds.
      # APK builds are handled by build_android.yml and release_android.yml

